- lib/solid/argument.ex
- lib/solid/tag.ex
- src/solid_parser.peg
- test/object_test.exs
- test/tag_test.exs
This moves the splitting of the key strings from `Argument.get` to the parser. This can optimize runtime if your strings are parsed at compile time.
> Parser now returns a list of strings for keys

- lib/solid.ex
- lib/solid/parser.ex
- mix.exs
- test/integration/custom_tag_test.exs
- test/integration/tags_test.exs
- test/support/custom_parsers.ex
- test/test_helper.exs
This PR changes a bit the way that custom tags are parsed. The custom tags to be parsed must be declared as part of a custom parser and passed to `Solid.parse`
Maybe in the future we could have it so that one could simply use `MyCustomParser.parse` and `MyCustomParser.render` ? This way it's very clear that customised tags are part of an extension of the original `Solid.Parser` ? And we wouldn't be parsing custom tags that are not declared and having a proper parsing failure?
cc/ @jalcine
> Change custom tags to be explicitly defined

- test/context_test.exs
- test/integration/custom_tag_test.exs
There’s currently a test that compares the output of the custom `current_date` tag against the string `"2020"`.
This means that in 2021, the test is now failing. This MR fixes this by comparing against the current year from `DateTime.utc_now/0`.
> Fix date integration test

- lib/solid/object.ex
- test/object_test.exs
Previously, Solid raised when trying to render a map in an object.
This is contrary to the behavior of the Liquid gem where maps used as
objects are instead inspected/stringified.
Here is the behavior of the Liquid gem that this change also brings to Solid:
```ruby
template = Liquid::Template.parse("{{ person }}")
assigns = {"person" => {"name" => "Jane Doe"}}
template.render(assigns)
=> "{\"name\"=>\"Jane Doe\"}"
```
> Allow stringizing of maps in objects

- lib/solid/filter.ex
- test/cases/035/input.json
- test/cases/035/input.liquid
- test/cases/037/input.json
- test/cases/037/input.liquid
Liquid does checking that the input responds to the list functions, this should be a safe version of that.
I am getting a failing test locally related to date, and it doesn't make any sense to me. It's unrelated to this PR as it happens on main.
> Allow first, last filters to work with non-lists

- test/integration/cases_test.exs
- test/test_helper.exs
While implementing [whitespace support](https://github.com/edgurgel/solid/pull/67) I came to the conclusion that it makes sense to [auto generate different whitespace trimming variants](https://github.com/edgurgel/solid/pull/67/files#diff-184a20c64c23513f3e8dd18847f5eb1a4dc6b0f2976c990175281f313b1006ca) of a given template to gain a good test coverage of edge cases while keeping test maintainable.
One problem I encountered, was that since the templates where generated I didn't know the actual input that was used when comparing the render results of liquid and solid.
My solution was adding a new `assert_render` macro that renders the template in liquid and solid and then compares them (as we do already with `cases_test`), but then includes the passed template in the assertion output if …
> Tests, Add New assert_render helper

- lib/solid/argument.ex
- lib/solid/parser.ex
- test/cases/114/input.json
- test/cases/114/input.liquid
- test/integration/cases_test.exs
- test/integration/custom_filter_test.exs
- test/liquid.rb
Adding as per:
https://github.com/Shopify/liquid/blob/50d1a2ffc91e69c26af2eea278cbc9c4930126a9/lib/liquid/variable.rb#L16-L17
[used by Shopify to translate strings with variable replacements](https://shopify.dev/tutorials/develop-theme-localization-use-translation-keys)
> Add support for named arguments in filters

- lib/solid/argument.ex
- lib/solid/context.ex
- test/cases/114/input.json
- test/cases/114/input.liquid
- test/context_test.exs
Shout out to @barkerja for finding and debugging this to find it was related to `Solid.Argument.get/3` 📣 🎩 🙇 
We discovered this due to a template doing the opposite of what we expected:
```elixir
iex(27)> Solid.parse!("{% if value == true %}true{% else %}false{% endif %}") |> Solid.render(%{"value" => true}) |> to_string
"true"
iex(28)> Solid.parse!("{% if value == false %}false{% else %}true{% endif %}") |> Solid.render(%{"value" => false}) |> to_string
"true"
```
The root cause is the use of [`Enum.find_value/3`](https://hexdocs.pm/elixir/Enum.html#find_value/3).
> The return value is considered to be found when the result is truthy (_neither nil nor false_).
I don't think my solution is particularly elegant, so if you want to refactor it a bit I won't be offended.  This is technically …
> fix bug that prevented using `false` as an argument

- lib/solid/parser/argument.ex
- lib/solid/parser/base.ex
- lib/solid/parser/variable.ex
- lib/solid/tag.ex
- test/integration/custom_tag_test.exs
- test/support/custom_parsers.ex
- test/support/custom_tags.ex
Propose a flexible way to define custom tag
1. Move expression for field and arguments to helper modules
2. Define a `behaviour` for custom tag
3. Add test for custom tag using module
To implement new custom tag you need to create new module that implement `CustomTag` behaviour:
```elixir
defmodule MyCustomTag do
import NimbleParsec
@behaviour Solid.Tag.CustomTag
@impl true
def spec() do
space = Solid.Parser.Literal.whitespace(min: 0)
ignore(string("{%"))
|> ignore(space)
|> ignore(string("my_tag"))
|> ignore(space)
|> ignore(string("%}"))
end
@impl true
def render(_context, _binding, _options) do
[text: "my first tag"]
end
end
```
- `spec` define how to parse your tag
- `render` define how to render your tag
Then add custom tag to your parser
```elixir
defmodule MyParser do
use …
```
> Implement tag behaviour for extend custom tag easier

- lib/solid.ex
- lib/solid/filter.ex
- test/integration/custom_filter_test.exs
When using this module in different parts of a codebase, one might
encounter the situation that a certain template needs a different set
of filters available than other templates.
The current approach of using application environment only allows for
a single custom filter module to be defined globally. This patch
changes that by creating a new option, `custom_filters:`, to be passed
in at render time.
> Allow custom filter module to be passed in through render option

- lib/solid/parser/base.ex
- test/integration/tags_test.exs
- test/support/custom_parsers.ex
This allows custom filters like "render" to be implemented using custom tags instead of the built-in ones.
I'm not sure if this is something you want, but I found myself in a situation where I cannot upgrade solid without breaking changes due to the implementation of render being different than my own (I share context while the built-in does not). So, I figure I'd PR it back at least.
> Allow standard tags to be removed from the parser

- lib/solid.ex
- lib/solid/argument.ex
- lib/solid/context.ex
- lib/solid/filter.ex
- test/argument_test.exs
- test/integration/filters_test.exs
Adds support for the `strict_filters` option that Liquid supports. This fixes #107
> Adds strict_filters option

- lib/solid/file_system.ex
Hey there, I think it’s a bit unexpected that hyphens are not accepted in template names. It took me quite a while until I had figured out what was going on 😅
> Allow hyphens in template names

- lib/solid/filter.ex
- test/cases/134/input.json
- test/cases/134/input.liquid
Hey there 👋 
This updates the `default` filter to return the fallback value for empty strings according to [spec](https://shopify.github.io/liquid/filters/default/).
Liquid:
```
$ echo 'Hello {{ name | default: "there" }}!' | liquid '{ "name": "" }'
Hello there!
```
Solid:
```
iex > "Hello {{ name | default: \"there\" }}!" |> Solid.parse!() |> Solid.render!(%{"name" => ""}) |> IO.puts()
Hello !
```
> Update default filter to return fallback value for empty strings

- lib/solid/context.ex
- lib/solid/parser/variable.ex
- test/context_test.exs
- test/integration/objects_test.exs
I took a shot at fixing #142 
Added an identifier to object access (i.e. between `[..]`). The tricky part is that ends up as a string when reaching `Context.get_in/3`, so you can't know if you want to access that value or the value a variable points to.
So I tagged the value with `:reference` (maybe that's not a great name). Then `Context.get_in/3` has to resolve what value that variable points to.
I wrote a test showing that a variable pointing to a variable pointing to a variable works but that may "just work" because of how the Assign works. So maybe that test is unnecessary.
That seems to work but I'm not sure if there's a better way to do this.
> Use a variable to access a hash

- lib/solid/expression.ex
- lib/solid/parser/literal.ex
- lib/solid/parser/variable.ex
- test/cases/if/input.json
- test/cases/if/input.liquid
- test/cases/object/input.liquid
This adds support for the `empty` keyword per [spec](https://shopify.github.io/liquid/basics/types/#emptydrop)
I think there's an issue where if a reserved word appears anywhere in the name of a var, it causes a problem. But this seems to occur for `nil` as well, so I think it's unrelated to this PR
> Adds support for empty per spec

- lib/solid/matcher.ex
- test/cases/for/input.json
- test/cases/for/input.liquid
This PR resolves #148, although the modified test case fails as Solid uses the builtin (unordered) maps whereas Liquid/Ruby appears to use ordered maps.
I tweaked the patch I included in the issue for when there are multiple accessors, but I'm not sure if that bit is correct.
> Add support for key-value pair access after map iteration

- README.md
- lib/solid/sigil.ex
- test/sigil_test.exs
I'm using Solid a lot in my project for writing AI prompts. This PR introduces a new `~LIQUID` sigil that validates Liquid templates at compile time. This provides several benefits:
1. Catches syntax errors early in the development cycle
2. Provides detailed error messages with line numbers and context
3. Improves developer experience by showing exactly where template errors occur
4. Pre-compiles templates for better runtime performance
The implementation includes:
- A new `Solid.Sigil` module with the `sigil_LIQUID` macro
- Comprehensive tests to verify error handling
- Documentation with examples
- A brief section in the README
Example of how errors are rendered inside Elixir application:
I'm also working on a VSCode extension for syntax highlighting of Liquid templates within these …
> Added ~LIQUID sigil

- README.md
As discussed, adding link to the readme. Hopefully it will work good enough 😂
> Mention liquid-sigil VS code extension in readme

- lib/solid/argument.ex
- lib/solid/standard_filter.ex
- lib/solid/tags/for_tag.ex
- lib/solid/variable.ex
- test/solid/integration/scenarios/filter/input.liquid
- test/solid/integration/scenarios/for/input.json
- test/solid/integration/scenarios/for/input.liquid
- test/solid/integration/scenarios/object/input.json
- test/solid/integration/scenarios/object/input.liquid
- test/solid/object_test.exs
- test/solid/variable_test.exs
* Fix  ranges rendering;
* `first` filter on ranges and maps;
* Fix parsing of bracket variables
* Handle maps as enumerable on `{% for %}`
> Assorted fixes

- lib/solid.ex
- test/solid_test.exs
Hello,
when both **strict_variables** and **strict_filters** options were enabled at the same time, the `Solid.render` function did not return an error if there was no strict variable error present at the same time. This is due to the precedence in the `cond` block.
The result was that the unknown filter errors were silently ignored, and the render function returned an :ok tuple.
> fix: Return error when both strict variables and filters are enabled
